### ISSUE TITLE
Got an error from sample code.

### ISSUE THREAD

**Issue by heytitle** [davidmogar/normalizr#4]
Hi, I tried the code in README. However I got this error. My Python is 2.7. 
```
Traceback (most recent call last):
  File "remove-accent.py", line 5, in <module>
    from normalizr import Normalizr
  File "/usr/local/lib/python2.7/site-packages/normalizr/__init__.py", line 3, in <module>
    from normalizr.normalizr import Normalizr
  File "/usr/local/lib/python2.7/site-packages/normalizr/normalizr.py", line 7, in <module>
    import normalizr.regex as regex
ImportError: No module named regex
```

**Comment by davidmogar** [comment]
Hi there heytitle. First of all thanks for using this lib. The problem here is that Normalizr only works with Python 3.3 & 3.4 as the home page says. I want to adapt it to 2.7 but I have to find some time.

Hope this can help ;)
